apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discord-bot.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "discord-bot.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "discord-bot.name" . }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: bot
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: {{ .Values.envSecret }}
          env:
            - name: HOME
              value: /home/bot
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: /repo/apps/discord-bot/logs
            - name: home
              mountPath: /home/bot
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: logs
          emptyDir: {}
        - name: home
          emptyDir: {}
        - name: tmp
          emptyDir: {}
