apiVersion: v1
kind: Namespace
metadata:
  name: metabase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
spec:
  type: ClusterIP
  ports:
  - name: http-web
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: metabase
---
# Enable metabase.k8s.quantifieduncertainty.org website.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-server-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: metabase.k8s.quantifieduncertainty.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metabase-service
            port: 80
  tls:
  - hosts:
    - metabase.k8s.quantifieduncertainty.org
    secretName: metabase-tls
