apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: common-ci
spec:
  serviceAccountName: quri-ci
  entrypoint: main

  templates:
  - name: main
    inputs:
      parameters:
      - name: github-org
        value: quantified-uncertainty # either `quantified-uncertainty` or `getguesstimate`

      - name: repo
        # required

      - name: branch
        value: main

      - name: image-name
        # required

      - name: argo-app
        # required

      - name: argo-namespace
        value: null # defaults to parameters.argo-app

    steps:
    - - name: build
        templateRef:
          name: docker-build
          template: main
        arguments:
          parameters:
          - name: github-org
            value: "{{`{{ inputs.parameters.github-org }}`}}"
          - name: repo
            value: "{{`{{ inputs.parameters.repo }}`}}"
          - name: branch
            value: "{{`{{ inputs.parameters.branch }}`}}"
          - name: image-name
            value: "{{`{{ inputs.parameters.image-name }}`}}"

    # TODO - send GitHub check

    - - name: deploy
        templateRef:
          name: apply-argocd-application
          template: main
        arguments:
          parameters:
          - name: name
            value: "{{`{{ inputs.parameters.argo-app }}`}}"
          - name: namespace
            value: "{{`{{ inputs.parameters.argo-namespace }}`}}"
          - name: image-tag
            # TODO - use exact git revision instead
            value: "{{`{{ inputs.parameters.branch }}`}}"

    # TODO - send Slack notification
