apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-build
spec:
  serviceAccountName: quri-ci
  entrypoint: main

  templates:
  - name: main
    inputs:
      parameters:
      - name: github-org
        value: quantified-uncertainty # default
      - name: repo
      - name: branch
        value: main # default
      - name: directory
        value: ""
      - name: image-name
    steps:
    - - name: get-revision
        template: get-revision
        arguments:
          parameters:
          - name: github-org
            value: "{{`{{ inputs.parameters.github-org }}`}}"
          - name: repo
            value: "{{`{{ inputs.parameters.repo }}`}}"
          - name: branch
            value: "{{`{{ inputs.parameters.branch }}`}}"
    - - name: build
        template: build
        arguments:
          parameters:
          - name: github-org
            value: "{{`{{ inputs.parameters.github-org }}`}}"
          - name: repo
            value: "{{`{{ inputs.parameters.repo }}`}}"
          - name: branch
            value: "{{`{{ inputs.parameters.branch }}`}}"
          - name: directory
            value: "{{`{{ inputs.parameters.directory }}`}}"
          - name: image-name
            value: "{{`{{ inputs.parameters.image-name }}`}}"
          - name: git-revision
            value: "{{`{{ steps.get-revision.outputs.result }}`}}"
    outputs:
      parameters:
      - name: git-revision
        value: "{{`{{ steps.get-revision.outputs.result }}`}}"

  - name: get-revision
    arguments:
      parameters:
      - name: github-org
      - name: repo
      - name: branch
      artifacts:
      - name: source
        path: /workspace
        git:
          repo: https://github.com/{{`{{ inputs.parameters.github-org }}`}}/{{`{{ inputs.parameters.repo }}`}}
          revision: "{{`{{ inputs.parameters.branch }}`}}"
    container:
      image: alpine/git
      workingDir: /workspace
      command: [git, rev-parse, HEAD]

  - name: build
    templates:
    inputs:
      parameters:
      - name: github-org
      - name: repo
      - name: branch
      - name: directory
      - name: image-name
      - name: git-revision

      artifacts:
      - name: source
        path: /workspace
        git:
          repo: https://github.com/{{`{{ inputs.parameters.github-org }}`}}/{{`{{ inputs.parameters.repo }}`}}
          revision: "{{`{{ inputs.parameters.branch }}`}}"

    volumes:
    - name: quri-registry-secret
      secret:
        secretName: quri-registry-write
    container:
      image: gcr.io/kaniko-project/executor:latest
      volumeMounts:
      - name: quri-registry-secret
        mountPath: /kaniko/.docker
      args:
      # tag with branch
      - "--destination=registry.digitalocean.com/quri/{{`{{ inputs.parameters.image-name }}`}}:{{`{{ inputs.parameters.branch }}`}}"
      # also tag with exact git revision
      - "--destination=registry.digitalocean.com/quri/{{`{{ inputs.parameters.image-name }}`}}:{{`{{ inputs.parameters.git-revision }}`}}"
      # use correct directory
      # TODO - support "run build from root but with specific subdirectory in monorepo" pattern
      - "--context=dir:///workspace/{{`{{ inputs.parameters.directory }}`}}"
      - "--dockerfile=/workspace/{{`{{ inputs.parameters.directory }}`}}/Dockerfile"
      - "--cache=true"
      - "--skip-default-registry-fallback"
