apiVersion: v1
kind: ServiceAccount
metadata:
  name: guesstimate-server-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-executor
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: enable-executor
subjects:
- kind: ServiceAccount
  name: guesstimate-server-ci
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: argo-executor
  apiGroup: rbac.authorization.k8s.io
