apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: guesstimate-server-ci
spec:
  serviceAccountName: guesstimate-server-ci
  entrypoint: all

  volumes:
  - name: quri-registry-secret
    secret:
      secretName: quri-registry

  templates:
  - name: all
    steps:
    - - name: obtain-github-token
        template: obtain-github-token
    - - name: build-and-push
        template: build-and-push
    - - name: apply-argocd-application
        template: apply-argocd-application

  - name: obtain-github-token
    container:
      image: ghcr.io/quantified-uncertainty/github-credentials-obtainer:latest
      env:
      - name: PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: quri-integrations-for-guesstimate-github-app
            key: private-key
      - name: APP_ID
        valueFrom:
          secretKeyRef:
            name: quri-integrations-for-guesstimate-github-app
            key: app-id
      - name: INSTALLATION_ID
        valueFrom:
          secretKeyRef:
            name: quri-integrations-for-guesstimate-github-app
            key: getguesstimate-installation-id
    outputs:
      parameters:
      - name: github-token
        valueFrom:
          path: /tmp/github-token
      - name: docker-config
        valueFrom:
          path: /tmp/docker-config.json

  - name: build-and-push
    inputs:
      artifacts:
      - name: source
        path: /workspace
        git:
          repo: {{ .Values.git.repo }}
          revision: {{ .Values.git.revision }}
    container:
      image: gcr.io/kaniko-project/executor:latest
      volumeMounts:
      - name: quri-registry-secret
        mountPath: /kaniko/.docker/config.json
      args: ["--destination=registry.digitalocean.com/quri/guesstimate-server",
             "--skip-default-registry-fallback",
             "--verbosity=debug"]

  - name: apply-argocd-application
    resource:
      action: apply
      # TODO:
      # - app name based on git branch
      # - remove app if branch is deleted
      # - correct image tag
      manifest: |-
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: guesstimate-server
          namespace: argocd
        spec:
          syncPolicy:
            automated:
              prune: true
          source:
            repoURL: 'https://github.com/quantified-uncertainty/ops'
            path: k8s/apps/guesstimate-server
            targetRevision: HEAD
            helm:
              valuesObject:
                version: "image-tag"
