apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global-config
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: slack
  receivers:
  - name: slack
    slackConfigs:
    - apiURL:
        name: slack-alerts
        key: slack-alerts
