apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global-config
spec:
  route:
    groupBy: ['alertname', 'namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: slack
    routes:
    - matchers:
      - name: alertname
        value: Watchdog
      receiver: drop
  receivers:
  - name: slack
    slackConfigs:
    - apiURL:
        name: slack-alerts
        key: slack-alerts
      sendResolved: true
      username: AlertManager
      title: |
        [{{`{{ .Status | toUpper -}}`}}
        {{`{{ if eq .Status "firing" }}`}}:{{`{{ .Alerts.Firing | len }}`}}{{`{{- end -}}`}}
        ] {{`{{ .GroupLabels.namespace }}`}}/{{`{{ .GroupLabels.alertname }}`}}
      text: |
        {{`{{- if (index .Alerts 0).Annotations.summary }}`}}
          {{`{{- "\n" -}}`}}
          *Summary:* {{`{{ (index .Alerts 0).Annotations.summary }}`}}
        {{`{{- end }}`}}
 
        {{`{{ range .Alerts }}`}}
          {{`{{- if .Annotations.description }}`}}
            {{`{{- "\n" -}}`}}
            {{`{{ .Annotations.description }}`}}
            {{`{{- "\n" -}}`}}
          {{`{{- end }}`}}
          {{`{{- if .Annotations.message }}`}}
            {{`{{- "\n" -}}`}}
            {{`{{ .Annotations.message }}`}}
            {{`{{- "\n" -}}`}}
          {{`{{- end }}`}}
        {{`{{- end }}`}}
      fields:
      - title: "Severity"
        value: "{{`{{ .CommonLabels.severity }}`}}"
  - name: drop
