# Basic Argo CD config; see https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argo.k8s.quantifieduncertainty.org
  # Important workaround for DigitalOcean Kubernetes; otherwise apps will be
  # permanently out of sync.
  # See also: https://github.com/argoproj/argo-cd/issues/10456#issuecomment-1249381338
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
  # Github auth.
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $dex-github-auth:clientID
          clientSecret: $dex-github-auth:clientSecret
          orgs:
          - name: quantified-uncertainty
