# https://argo-workflows.readthedocs.io/en/release-3.5/argo-server-sso-argocd/#example-manifests-for-authenticating-against-argo-cds-dex-kustomize
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
        - name: dex
          env:
            - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argo-workflows-sso
                  key: clientSecret
