apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.3/manifests/install.yaml
- resources/ingress.yaml

patches:
- path: patches/inject-workflows-sso-secret.yaml
- path: patches/config.yaml
- path: patches/rbac.yaml
