apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    # This is a kustomize source, because we don't want to set up Argo CD from the Helm chart
    # (I had some issues with it)
    repoURL: https://github.com/quantified-uncertainty/ops
    path: k8s/apps/argocd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
