apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - chart: argo-workflows
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.40.14 # https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/Chart.yaml
      helm:
        valuesObject:
          server:
            ingress:
              # enabled: true
              # annotations:
              #   cert-manager.io/cluster-issuer: letsencrypt-prod
              # ingressClassName: nginx
              # tls:
              # - hosts:
              #   - argo-workflows.k8s.quantifieduncertainty.org
              #   secretName: argo-workflows-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
