apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  # This is a kustomize source, because we don't want to set up Argo CD from the Helm chart
  # (I had some issues with it)
  - path: k8s/apps/argocd
    repoURL: 'https://github.com/quantified-uncertainty/ops'
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
