apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/quantified-uncertainty/ops
    path: k8s/apps/argo-workflows
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
