apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      valuesObject:
        controller:
          extraArgs:
            "enable-ssl-passthrough": "" # necessary for proxying to ArgoCD
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
