# Simplified configuration for Argo CD.
# All apps in the following list will be turned into Argo CD Applications.
# If `source` is set, it'll load a remote Helm chart. See https://argo-cd.readthedocs.io/en/stable/user-guide/helm/ for the supported fields in the `source` section.
# Otherwise, it'll load the `k8s/apps/{name}` dir from this repo.
# (If this sounds confusing, check out the `apps.yaml` template file, and look through Argo CD docs on `Application` resource.)

apps:
# -------------------- Infra-level apps --------------------
#
# For infra-level apps, `automated: null` is set intentionally to avoid accidents.
# Please sync them via [Argo CD Web UI](https://argo.k8s.quantifieduncertainty.org/) or CLI,
# and check the diffs carefully before sync.
- name: argocd
  automated: null

- name: argo-workflows
  automated: null

- name: argocd-image-updater
  automated: null

- name: registry

# Core services for ingress
- name: cert-manager
  automated: null

- name: ingress-nginx
  automated: null
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      valuesObject:
        controller:
          extraArgs:
            "enable-ssl-passthrough": "" # necessary for proxying to ArgoCD

# Metrics and observability
- name: metrics-server
  namespace: kube-system # why not, it's usually there
  automated: null
  source:
    chart: metrics-server
    targetRevision: "3.12.1"
    repoURL: https://kubernetes-sigs.github.io/metrics-server

- name: prometheus
  automated: null
  # Argo CD is having some trouble with Prometheus CRDs (they're too large).
  # It might be useful to deploy
  # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds
  # as a separate Application instead of enabling ServerSideApply for all
  # Prometheus resources.
  # See also: https://github.com/argoproj/argo-cd/issues/820
  syncOptions:
  - ServerSideApply=true

- name: loki
  automated: null

# PostgresQL operator
- name: cnpg
  automated: null
  namespace: cnpg-system # default namespace used in cnpg docs
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.20.1

# ECK - operator for managing Elastic (this app won't deploy any Elasticsearch clusters by itself)
- name: elastic-system
  automated: null

# -------------------- Analytics --------------------
- name: metabase
  info:
  - name: URL
    value: https://metabase.k8s.quantifieduncertainty.org

# -------------------- CI --------------------
# CI for all apps and common CI workflows for Argo Workflows
- name: quri-ci

# -------------------- QURI apps --------------------
- name: elastic
  # Namespaced for historical reasons; metaforecast is the only app that uses this chart, for now.
  # But we will probably use a single Elastic cluster (possibly with multiple users) for all QURI apps.
  namespace: metaforecast
  automated: null

- name: metaforecast
  source:
    repoURL: https://github.com/quantified-uncertainty/squiggle
    path: apps/metaforecast/ops/chart
    targetRevision: main
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/quantified-uncertainty/metaforecast
  automated: null

- name: gucem
  source:
    repoURL: git@github.com/quantified-uncertainty/GUCEM.git
    path: ops/chart
    targetRevision: "2024"

# Note: some user-facing apps such as Guesstimate are deployed by Argo Workflows dynamically, so they are not listed here.
# Check out apply-argocd-application WorkflowTemplate in argo-ci app to see how they're configured.
