apps:
# Infra-level apps
- name: argocd
  automated: null

- name: argo-workflows
  automated: null

- name: cert-manager
  automated: null

- name: cnpg
  automated: null
  namespace: cnpg-system # default namespace used in cnpg docs
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.20.1

- name: ingress-nginx
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      valuesObject:
        controller:
          extraArgs:
            "enable-ssl-passthrough": "" # necessary for proxying to ArgoCD

# Analytics and monitoring
- name: metabase
  info:
  - name: URL
    value: https://metabase.k8s.quantifieduncertainty.org

- name: prometheus
  # Argo CD is having some trouble with Prometheus CRDs (they're too large).
  # It might be useful to deploy
  # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds
  # as a separate Application instead of enabling ServerSideApply for all
  # Prometheus resources.
  # See also: https://github.com/argoproj/argo-cd/issues/820
  syncOptions:
  - ServerSideApply=true

- name: loki
  syncOptions:
  - ServerSideApply=true
  automated: null
  sources:
  - chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    helm:
      valuesObject:
        loki:
          enabled: true
          # TODO - persistence
        promtail:
          enabled: true
        fluent-bit:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          enabled: false

# CI and templates
- name: guesstimate-server-ci
  namespace: quri-ci

# Note: guesstimate-server app is deployed by Argo Workflows dynamically, so it's not listed here.
