apps:
# Infra-level apps.
# If `source` is set, it'll load a remote Helm chart.
# Otherwise, it'll load the `k8s/apps/{name}` dir from this repo.
#
# For infra-level apps, `automated: null` is set intentionally to avoid accidents.
# Please sync them through Argo CD Web UI or CLI, and check the diffs carefully before sync.
- name: argocd
  automated: null

- name: argo-workflows
  automated: null

# Core services for ingress
- name: cert-manager
  automated: null

- name: ingress-nginx
  automated: null
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      valuesObject:
        controller:
          extraArgs:
            "enable-ssl-passthrough": "" # necessary for proxying to ArgoCD

# Metrics and observability
- name: metrics-server
  namespace: kube-system # why not, it's usually there
  automated: null
  source:
    chart: metrics-server
    targetRevision: "3.12.1"
    repoURL: https://kubernetes-sigs.github.io/metrics-server

- name: kubernetes-dashboard
  automated: null
  source:
    chart: kubernetes-dashboard
    targetRevision: "7.2.0"
    repoURL: https://kubernetes.github.io/dashboard
    helm:
      valuesObject:
        ingress:
          enabled: true

- name: prometheus
  automated: null
  # Argo CD is having some trouble with Prometheus CRDs (they're too large).
  # It might be useful to deploy
  # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds
  # as a separate Application instead of enabling ServerSideApply for all
  # Prometheus resources.
  # See also: https://github.com/argoproj/argo-cd/issues/820
  syncOptions:
  - ServerSideApply=true

- name: loki
  automated: null

# PostgresQL operator
- name: cnpg
  automated: null
  namespace: cnpg-system # default namespace used in cnpg docs
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.20.1

# ECK - operator for managing Elastic (this app won't deploy any Elasticsearch clusters by itself)
- name: elastic-system
  automated: null

# Analytics
- name: metabase
  info:
  - name: URL
    value: https://metabase.k8s.quantifieduncertainty.org

# CI and templates
- name: guesstimate-server-ci
  namespace: quri-ci

# Note: guesstimate-server app is deployed by Argo Workflows dynamically, so it's not listed here.

# QURI apps
- name: metaforecast
