apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name | required "name is required" }}-oauth2-proxy"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: "{{ .Values.name }}-oauth2-proxy"
  template:
    metadata:
      labels:
        k8s-app: "{{ .Values.name }}-oauth2-proxy"
    spec:
      containers:
      - args:
        - --provider=github
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --email-domain=*
        - --github-org={{ .Values.auth.github_org }}
        - --github-team={{ .Values.auth.github_team }}
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.oauth_secret }}"
              key: clientID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.oauth_secret }}"
              key: clientSecret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.oauth_secret }}"
              key: cookieSecret
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-oauth2-proxy"
spec:
  ports:
  - port: 4180
    targetPort: 4180
  selector:
    k8s-app: "{{ .Values.name }}-oauth2-proxy"
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.name }}-oauth2-proxy"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.host | required "host is required" }}"
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.name }}-oauth2-proxy"
            port:
              number: 4180
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.name }}-tls
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.name }}"
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name | required "service.name is required" }}
            port:
              number: {{ .Values.service.port | required "service.port is required" }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.name }}-tls
