grafana_host: grafana.k8s.quantifieduncertainty.org
prometheus_host: prometheus.k8s.quantifieduncertainty.org
alertmanager_host: alerts.k8s.quantifieduncertainty.org

kube-prometheus-stack:
  # Based on https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/04-setup-observability/assets/manifests/prom-stack-values-v35.5.1.yaml

  # Disable `etcd` and `kubeScheduler` rules (managed by DOKS, so metrics are not accesible)
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeScheduler: false

  # Disabled because it's being managed by DOKS, so it's not accessible
  kubeScheduler:
    enabled: false

  # Disabled because it's being managed by DOKS, so it's not accessible
  kubeEtcd:
    enabled: false

  alertmanager:
    enabled: true

  grafana:
    enabled: true
    admin:
      existingSecret: grafana-credentials # created by terraform/stacks/k8s

    # Starter Kit setup for DigitalOcean Block Storage
    persistence:
      enabled: true
      storageClassName: do-block-storage
      accessModes: ["ReadWriteOnce"]
      size: 5Gi

  prometheusOperator:
    enabled: true

  prometheus:
    enabled: true

    # additionalServiceMonitors:
    # # Uncomment the following section to enable ingress-nginx service monitoring
    #   - name: "ingress-nginx-monitor"
    #     selector:
    #       matchLabels:
    #         app.kubernetes.io/name: ingress-nginx
    #     namespaceSelector:
    #       matchNames:
    #         - ingress-nginx
    #     endpoints:
    #       - port: "metrics"

    # Prometheus StorageSpec for persistent data
    # ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
    prometheusSpec:
      # via https://github.com/prometheus-community/helm-charts/issues/1911 (note that last comment has a few typos)
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: do-block-storage
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
