apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /data/url
      value: https://argocd.staging.k8s.quantifieduncertainty.org
  target:
    kind: ConfigMap
    name: argocd-cm
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: argocd.staging.k8s.quantifieduncertainty.org
    - op: replace
      path: /spec/rules/0/host
      value: argocd.staging.k8s.quantifieduncertainty.org
  target:
    kind: Ingress
    name: argocd-server-ingress
