# This workflow applies an ArgoCD Application manifest to Kubernetes.
#
# This is useful for Argo Workflows-powered CI/CD, where we want to update `image.tag` on deployment,
# and don't want to bother with the GitOps pattern of committing the updated tag value to the repo.
#
# The common use case is to call this workflow as a step in a CI workflow after the build, to hand off the updated image to ArgoCD.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: apply-argocd-application
spec:
  serviceAccountName: quri-ci
  entrypoint: main

  templates:
  - name: main
    inputs:
      parameters:
      - name: name
        # required

      - name: namespace
        value: "" # defaults to argo-app

      - name: image-tag
        # required, will be used for image.tag Helm var

    resource:
      action: apply
      manifest: |-
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: {{`{{ inputs.parameters.name }}`}}
          namespace: argocd
        spec:
          project: default
          syncPolicy:
            syncOptions:
            - CreateNamespace=true
            automated:
              prune: true
          source:
            repoURL: https://github.com/quantified-uncertainty/ops
            path: k8s/apps/{{`{{ inputs.parameters.name }}`}}
            targetRevision: HEAD
            helm:
              valuesObject:
                image:
                  tag: {{`{{ inputs.parameters.image-tag }}`}}
          destination:
            server: https://kubernetes.default.svc
            namespace: {{`{{= inputs.parameters.namespace == '' ? inputs.parameters.name : inputs.parameters.namespace }}`}}
