# Build a docker container from Github repo and deploy it as Argo CD app.
# For Squiggle monorepo, you'll need monorepo-ci workflow, not this one.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: common-ci
spec:
  serviceAccountName: quri-ci
  entrypoint: main

  templates:
  - name: main
    inputs:
      parameters:
      - name: github_org
        default: quantified-uncertainty
        enum:
        - quantified-uncertainty
        - getguesstimate

      - name: repo
        # required

      - name: branch
        default: main

      - name: image_name
        # required

      - name: argo_app
        description: |
          Argo CD Application name; application will be sourced from k8s/apps/<name> dir in ops repo, similarly to static apps from `app-manifests/values.yaml`.

      - name: argo_namespace
        default: ""
        description: |
          Kubernetes namespace that will be used for deployment. Defaults to the value from `argo_app`.

    steps:
    - - name: build
        templateRef:
          name: docker-build
          template: main
        arguments:
          parameters:
          - name: github_org
            value: "{{`{{ inputs.parameters.github_org }}`}}"
          - name: repo
            value: "{{`{{ inputs.parameters.repo }}`}}"
          - name: branch
            value: "{{`{{ inputs.parameters.branch }}`}}"
          - name: image_name
            value: "{{`{{ inputs.parameters.image_name }}`}}"

    # TODO - send GitHub check

    - - name: deploy
        templateRef:
          name: apply-argocd-application
          template: main
        arguments:
          parameters:
          - name: name
            value: "{{`{{ inputs.parameters.argo_app }}`}}"
          - name: namespace
            value: "{{`{{= inputs.parameters.argo_namespace == '' ? inputs.parameters.argo_app : inputs.parameters.argo_namespace }}`}}"
          - name: image_tag
            # use exact git revision, not just branch name that could change - this will help with rollbacks and debugging
            value: "{{`{{ steps.build.outputs.parameters.git_revision }}`}}"

    # TODO - send Slack notification
