apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-build
spec:
  serviceAccountName: quri-ci
  entrypoint: main

  templates:
  - name: main
    inputs:
      parameters:
      - name: github-org
        default: quantified-uncertainty
      - name: repo
      - name: branch
        default: main
      - name: directory
        default: ""
        # If set, will build from this subdirectory of the repo.
        # Note that you can't reference parent directories in the Dockerfile, so if you need that, you might need to set `dockerfile` param instead.
      - name: dockerfile
        default: Dockerfile
      - name: image-name
    steps:
    - - name: get-revision
        template: get-revision
        arguments:
          parameters:
          - name: github-org
            value: "{{`{{ inputs.parameters.github-org }}`}}"
          - name: repo
            value: "{{`{{ inputs.parameters.repo }}`}}"
          - name: branch
            value: "{{`{{ inputs.parameters.branch }}`}}"
    - - name: build
        template: build
        arguments:
          parameters:
          - name: github-org
            value: "{{`{{ inputs.parameters.github-org }}`}}"
          - name: repo
            value: "{{`{{ inputs.parameters.repo }}`}}"
          - name: branch
            value: "{{`{{ inputs.parameters.branch }}`}}"
          - name: directory
            value: "{{`{{ inputs.parameters.directory }}`}}"
          - name: dockerfile
            value: "{{`{{ inputs.parameters.dockerfile }}`}}"
          - name: image-name
            value: "{{`{{ inputs.parameters.image-name }}`}}"
          - name: git-revision
            value: "{{`{{ steps.get-revision.outputs.result }}`}}"
    outputs:
      parameters:
      - name: git-revision
        valueFrom:
          parameter: "{{`{{ steps.get-revision.outputs.result }}`}}"

  - name: get-revision
    inputs:
      parameters:
      - name: github-org
      - name: repo
      - name: branch
      artifacts:
      - name: source
        path: /workspace
        git:
          repo: https://github.com/{{`{{ inputs.parameters.github-org }}`}}/{{`{{ inputs.parameters.repo }}`}}
          revision: "{{`{{ inputs.parameters.branch }}`}}"
          depth: 1
    container:
      image: alpine/git
      workingDir: /workspace
      command: [git, rev-parse, HEAD]

  - name: build
    templates:
    inputs:
      parameters:
      - name: github-org
      - name: repo
      - name: branch
      - name: directory
      - name: dockerfile
      - name: image-name
      - name: git-revision

      artifacts:
      - name: source
        path: /workspace
        git:
          repo: https://github.com/{{`{{ inputs.parameters.github-org }}`}}/{{`{{ inputs.parameters.repo }}`}}
          # note that we check out the exact revision obtained by get-revision step, not the branch, for consistency
          revision: "{{`{{ inputs.parameters.git-revision }}`}}"
          depth: 1

    volumes:
    - name: dockerconfig
      secret:
        secretName: dockerconfig
        items:
          - key: .dockerconfigjson
            path: config.json

    tolerations:
    - key: dedicated
      operator: Equal
      value: builds
      effect: NoSchedule

    container:
      image: gcr.io/kaniko-project/executor:latest
      volumeMounts:
      - name: dockerconfig
        mountPath: /kaniko/.docker
      args:
      # tag with branch
      - "--destination=registry.k8s.quantifieduncertainty.org/{{`{{ inputs.parameters.image-name }}`}}:{{`{{ inputs.parameters.branch }}`}}"
      # also tag with exact git revision
      - "--destination=registry.k8s.quantifieduncertainty.org/{{`{{ inputs.parameters.image-name }}`}}:{{`{{ inputs.parameters.git-revision }}`}}"
      # use correct directory
      # TODO - support "run build from root but with specific subdirectory in monorepo" pattern
      - "--context=dir:///workspace/{{`{{ inputs.parameters.directory }}`}}"
      - "--dockerfile={{`{{ inputs.parameters.dockerfile }}`}}"
      - "--cache=true"
      # helps with memory consumption, https://github.com/GoogleContainerTools/kaniko?tab=readme-ov-file#flag---compressed-caching
      - "--compressed-caching=false"
      - "--skip-default-registry-fallback"
