# This template outputs a github token that can be useful for github integrations later on, to match Github Actions functionality.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: github-token
spec:
  serviceAccountName: quri-ci
  entrypoint: main

  templates:
  - name: main
    inputs:
      parameters:
      - name: github-org # either `quantified-uncertainty` or `getguesstimate`
        default: quantified-uncertainty
    container:
      image: registry.k8s.quantifieduncertainty.org/quri/github-credentials-obtainer
      imagePullSecrets:
      - name: dockerconfig
      env:
      - name: PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: quri-integrations-for-{{`{{ inputs.parameters.github-org }}`}}-github-app
            key: private-key
      - name: APP_ID
        valueFrom:
          secretKeyRef:
            name: quri-integrations-for-{{`{{ inputs.parameters.github-org }}`}}-github-app
            key: app-id
      - name: INSTALLATION_ID
        valueFrom:
          secretKeyRef:
            name: quri-integrations-for-{{`{{ inputs.parameters.github-org }}`}}-github-app
            key: installation-id
    outputs:
      parameters:
      - name: github-token
        valueFrom:
          path: /tmp/github-token
