apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: guesstimate-server-ci
spec:
  serviceAccountName: quri-ci
  entrypoint: main

  templates:
  - name: main
    steps:
    - - name: call-common-ci
        templateRef:
          name: common-ci
          template: main
        arguments:
          parameters:
          - name: github_org
            value: getguesstimate
          - name: repo
            value: guesstimate-server
          - name: branch
            value: main
          - name: image_name
            value: guesstimate-server
          - name: argo_app
            value: guesstimate-server
          - name: argo_namespace
            value: guesstimate
