# This workflow is the CI step of the Squiggle Hub deployment.
# It builds the Hub docker image (which contains only a build script, for now; the Hub itself runs on Vercel),
# and then deploys the Hub to ArgoCD, by pushing the updated Application manifest to Kubernetes.
#
# ArgoCD handles the CD part: applies the manifest and rolls out the new Docker image.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: squiggle-ci
spec:
  serviceAccountName: quri-ci
  entrypoint: main

  templates:
  - name: main
    steps:
    # Build the docker image. See `turbo-to-docker.yaml` for details.
    - - name: turbo-to-docker
        templateRef:
          name: turbo-to-docker
          template: main
        arguments:
          parameters:
          - name: repo-url
            value: https://github.com/quantified-uncertainty/squiggle
          - name: package
            value: "@quri/hub"
          - name: output-directory
            value: apps/hub/dist
          - name: image-name
            value: squiggle-build-runner
          - name: turbo-build-command
            value: bundle

    - - name: deploy
        templateRef:
          name: apply-argocd-application
          template: main
        arguments:
          parameters:
          - name: name
            value: squiggle
          - name: image-tag
            # use exact git revision, not just branch name that could change - this will help with rollbacks and debugging
            value: "{{`{{ steps.turbo-to-docker.outputs.parameters.git-revision }}`}}"
