apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: squiggle-ci
spec:
  serviceAccountName: quri-ci
  entrypoint: main

  templates:
  - name: main
    steps:
    - - name: turbo-to-docker
        templateRef:
          name: turbo-to-docker
          template: main
        arguments:
          parameters:
          - name: repo-url
            value: https://github/quantified-uncertainty/squiggle
          - name: package
            value: "@quri/hub"
          - name: output-directory
            value: packages/hub/dist
          - name: image-name
            value: squiggle-build-runner

    - - name: deploy
        templateRef:
          name: apply-argocd-application
          template: main
        arguments:
          parameters:
          - name: name
            value: squiggle
          - name: image-tag
            # use exact git revision, not just branch name that could change - this will help with rollbacks and debugging
            value: "{{`{{ steps.turbo-to-docker.outputs.parameters.git-revision }}`}}"
