# Staging-specific app-of-apps for automated infrastructure deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-staging
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: k8s/app-manifests-staging
    repoURL: https://github.com/quantified-uncertainty/ops
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
