_onBuildServer: &onBuildServer
  nodeSelector:
    dedicated: builds
  tolerations:
  - key: dedicated
    operator: Equal
    value: builds
    effect: NoSchedule

harbor:
  existingSecretAdminPassword: harbor-admin-password

  expose:
    tls:
      certSource: secret
      secret:
        secretName: harbor-tls
    ingress:
      className: nginx
      hosts:
        core: harbor.k8s.quantifieduncertainty.org
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod

  externalURL: https://harbor.k8s.quantifieduncertainty.org

  persistence:
    persistentVolumeClaim:
      registry:
        size: 20Gi

  nginx:
    <<: *onBuildServer
  portal:
    <<: *onBuildServer
  core:
    <<: *onBuildServer
  jobservice:
    <<: *onBuildServer
  registry:
    <<: *onBuildServer
  trivy:
    <<: *onBuildServer
  database:
    <<: *onBuildServer
  redis:
    <<: *onBuildServer
  exporter:
    <<: *onBuildServer
    