apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-quri
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quri-es-http
            port:
              number: 9200
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Release.Name }}-quri-tls
