apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metabase
  labels:
    app: {{ .Release.Name }}-metabase
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-metabase
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-metabase
    spec:
      containers:
        - name: metabase
          image: "metabase/metabase:{{ .Values.version }}"
          imagePullPolicy: IfNotPresent
          env:
          - name: MB_DB_TYPE
            value: postgres
          - name: MB_DB_CONNECTION_URI
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-pg-app"
                key: jdbc-uri
          - name: MAX_SESSION_AGE
            value: "129600" # 3 months; https://www.metabase.com/docs/latest/operations-guide/changing-session-expiration.html
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: "700Mi"
            limits:
              memory: "2048Mi"
