argo-workflows:
  server:
    # explained here: https://argo-workflows.readthedocs.io/en/latest/argo-server-sso-argocd/
    authModes:
    - sso
    sso:
      enabled: true
      rbac:
        enabled: false
      issuer: https://argo.k8s.quantifieduncertainty.org/api/dex
      clientId:
        name: argo-workflows-sso
        key: clientID
      clientSecret:
        name: argo-workflows-sso
        key: clientSecret
      redirectUrl: https://workflows.k8s.quantifieduncertainty.org/oauth2/callback

    # Public hostname with HTTPS
    ingress:
      enabled: true
      hosts:
      - workflows.k8s.quantifieduncertainty.org
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      tls:
      - hosts:
        - workflows.k8s.quantifieduncertainty.org
        secretName: argo-workflows-tls

  controller:
    workflowDefaults:
      spec:
        podGC:
          strategy: OnPodCompletion

    links:
    - name: Chat
      scope: chat
      url: https://quri.slack.com

    - name: Pod Logs
      scope: pod-logs
      url: |-
        http://grafana.k8s.quantifieduncertainty.org/explore?left=["${status.startedAt}","${status.finishedAt}","Loki",{"expr":"{namespace=\"${metadata.namespace}\", pod=\"${metadata.name}\"}}"]


  artifactRepository:
    s3:
      # Sorry for hardcoding these, Argo Workflows chart doesn't allow to read these from a configmap or secret.
      bucket: quri-workflows-artifacts
      endpoint: nyc3.digitaloceanspaces.com
      accessKeySecret:
        name: workflows-artifacts-cred
        key: accessKey
      secretKeySecret:
        name: workflows-artifacts-cred
        key: secretKey
