apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.14.3
      helm:
        valuesObject:
          installCRDs: true
    - path: k8s/apps/cert-manager
      repoURL: 'https://github.com/quantified-uncertainty/ops'
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
