apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    path: k8s/apps/metabase
    repoURL: 'https://github.com/quantified-uncertainty/ops'
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: metabase
