apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      # Note: prometheus-stack has tons of huge CRDs, which are hard to ArgoCD to process, and also won't be updated by Helm.
      # So when you update this, check out
      # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#upgrading-chart,
      # which will give you a few kubectl commands to run by hand.
      # See also: this issue: https://github.com/argoproj/argo-cd/issues/820
      targetRevision: "56.21.4"
      helm:
        valueFiles:
          # explained here: https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
          - $values/values.yaml
    - repoURL: 'https://github.com/quantified-uncertainty/ops'
      path: k8s/apps/prometheus-stack
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
