# https://argo-workflows.readthedocs.io/en/release-3.5/argo-server-sso-argocd/#example-manifests-for-authenticating-against-argo-cds-dex-kustomize
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      volumes:
      - name: static-files
        emptyDir: {}
      - name: argo-workflows-sso
        secret:
          secretName: argo-workflows-sso
          optional: true
      containers:
      - name: dex
        volumeMounts:
        - mountPath: /shared
          name: static-files
        - mountPath: /tmp/argo-workflows-sso
          name: argo-workflows-sso
          readOnly: true
