apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  labels:
    app: {{ include "name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "name" . }}
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      containers:
        - name: server
          image: "{{ .Values.image.name }}:{{ required "tag is required" .Values.image.tag }}"
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: {{ .Values.envSecret }}
          env:
          - name: RAILS_ENV
            value: production
          - name: PORT
            value: "{{ .Values.port }}"
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.path }}
              port: {{ .Values.port }}
            {{- toYaml .Values.probe.liveness | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.path }}
              port: {{ .Values.port }}
            {{- toYaml .Values.probe.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
