---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "name" . }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  {{- range $host := .Values.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "name" $ }}
            port:
              number: 80
  {{- end }}
  tls:
  - hosts:
    {{- toYaml .Values.hosts | nindent 4 }}
    secretName: {{ include "name" . }}-tls
