{{- range $jobname, $job := .Values.jobs }}
---  
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ $jobname }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ $job.schedule | required "schedule is required" }}
  timeZone: Etc/UTC
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
          - name: {{ $.Values.image.pullSecret }}
          containers:
          - name: cronjob
            image: "{{ $.Values.image.name }}:{{ required "tag is required" $.Values.image.tag }}"
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: {{ $.Values.envSecret }}
            env:
            - name: RAILS_ENV
              value: production
            command:
              {{- $job.command | required "command is required" | toYaml | nindent 12 }}
{{- end }}
